server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liga?currentSchema=medical
    username: postgres
    password: dargo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    initialization-mode: always
    continue-on-error: true
    schema: classpath:init/schema.sql
    data: classpath:init/data.sql

