server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liga?currentSchema=medical
    username: postgres
    password: dargo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
      data-locations: classpath:init/schema.sql