server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liga?currentSchema=medical
    hikari:
      maximum-pool-size: 10
      jdbc-url: jdbc:postgresql://localhost:5432/liga?currentSchema=medical
      username: postgres
      password: dargo
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: ${LIQUIBASE_ENABLE:true}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: person-service.log

management:
  endpoints:
    web:
      exposure:
        include: "*"