server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liga?currentSchema=medical
    hikari:
      maximum-pool-size: 10
      jdbc-url: jdbc:postgresql://localhost:5432/liga?currentSchema=medical
      username: postgres
      password: dargo
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: ${LIQUIBASE_ENABLE:false}
  configuration:
    map-underscore-to-camel-case: true
